/* ============================================================
   ImpactHub Job Dashboard — data
   Sources:
   - Indeed resume profile (skills, certifications, work history,
     preferences) pulled 2026-07-18
   - Gmail application/interview emails, 2026-03-01 → 2026-07-17
   To update: edit APPLICATIONS below (newest first) and refresh
   SKILL_SETS if your Indeed skill list changes.
   ============================================================ */

const AS_OF = "July 18, 2026";

const PROFILE = {
  name: "Brian Richards",
  location: "Jersey City, NJ",
  email: "richards.brian86@gmail.com",
  preferredTitles: ["AI Operations Associate", "Junior AI Developer", "Cook / Prep"],
  minSalary: "$70,000/yr target",
  workHistory: [
    { role: "Head Instructor & Program Developer", org: "Brazilian Jiu-Jitsu", when: "Sep 2025 – Present" },
    { role: "Grill Cook / Station Lead", org: "Eurest (Compass Group)", when: "Jun 2024" },
    { role: "Kitchen Supervisor", org: "Samesa", when: "Mar 2021" },
    { role: "Kitchen Coordinator", org: "Variety Boys and Girls Club", when: "Sep 2020" },
    { role: "Kitchen Manager", org: "Nom Wah Nolita", when: "Sep 2019" },
    { role: "Operations & Management Lead", org: "Food Service Industry", when: "Jul 2019" }
  ],
  certifications: [
    "ServSafe", "ServSafe Food Handler Certification", "NYC Food Handlers Certificate",
    "Food Handler Certification", "Food Safety Certification", "SORA",
    "Paraprofessional Certification", "Special Education Certification"
  ]
};

/* Every string below is copied verbatim from the Indeed skills list,
   so each matched trait on a job card is an exact skill you hold today. */
const SKILL_SETS = {
  AI_CORE: ["Prompt engineering", "Generative AI", "AI models", "AI-driven automation",
    "Machine learning (ML) fundamentals", "Natural language processing",
    "AI platforms (beyond public GPTs)", "Generative models", "Machine intelligence",
    "Claude", "OpenAI", "Codex", "Manus"],
  DEV: ["Full-stack development", "Software engineering", "Python", "Node.js",
    "PostgreSQL", "APIs", "Application design", "Application Integration",
    "Schema design", "Data model design", "Database software proficiency",
    "System development", "Requirements design", "Prototypes", "Documentation"],
  CLOUD_OPS: ["Cloud-based systems", "DevOps automation", "Cloud solution engineering",
    "Automation", "Azure AD", "Windows", "Google Workspace", "Airtable", "Make",
    "Computer operation", "Productivity software"],
  DATA_AI: ["Predictive modeling analysis", "Data modeling projects",
    "Data-driven problem-solving", "Machine learning projects",
    "Machine learning frameworks", "Artificial intelligence research",
    "Developing large-scale AI models", "Research"],
  COOKING: ["Knife skills", "Mise en place", "Kitchen station setup", "Plating",
    "Grilling", "Food preparation", "Meal Preparation", "Recipe adherence",
    "Pre-cooking preparation", "Cooking", "Food handling", "Flat-top griddles",
    "Food steamers", "Food processors", "Sous vide", "Food production"],
  FOOD_SAFETY: ["Food safety", "Food safety management", "Food hygiene",
    "Food allergen awareness", "Sanitation procedures",
    "Food service health code compliance", "Food sanitation practices",
    "Kitchen health and safety standards", "Food service workstation cleanliness"],
  KITCHEN_LEAD: ["Supervising experience", "Kitchen organization", "Food ordering",
    "Inventory records", "Managing hospitality teams", "Food management",
    "Team motivation (leadership skill)", "Leadership", "Conflict management",
    "Managing projects", "Process Optimization"],
  CULINARY_EXP: ["Culinary experience", "Kitchen experience", "Restaurant experience",
    "Fine dining experience", "Japanese cuisine", "Catering", "Hospitality",
    "Food service", "Food industry"],
  TEACHING: ["Teaching", "Classroom experience", "Classroom management",
    "Classroom behavior management", "Working with children",
    "Curriculum implementation", "Instructor-led training (training delivery method)",
    "Physical assistance for special education students", "Safe environment creation"],
  MARTIAL_ARTS: ["Martial arts", "Martial arts coaching experience",
    "Mixed martial arts", "Judo", "Sports coaching", "Group fitness"],
  SECURITY: ["Patrolling", "Threat assessment", "Loss prevention",
    "Surveillance reporting", "Incident Reporting",
    "Safety protocol implementation", "Safe work practices"],
  CUSTOMER: ["Customer service", "Customer inquiry handling", "Customer communication",
    "Greeting customers", "Customer retention", "Cross-selling", "Cash Handling",
    "POS systems", "Serving"],
  LABOR: ["Manual handling", "Outdoor work", "Maintaining an organized workspace",
    "Safe work practices", "Dishwashing", "Sanitation procedures"],
  CORE: ["Attention to detail", "Time management", "Dependability", "Teamwork",
    "Communication skills", "Written communication", "Accountability",
    "Flexibility", "Creativity", "Decisiveness", "Stakeholder management",
    "Cross-functional communication", "Marketing"]
};

const CATEGORIES = {
  ai:        { label: "AI & Software",        slot: 1 },
  culinary:  { label: "Culinary & Food Service", slot: 2 },
  education: { label: "Education & Coaching", slot: 3 },
  civic:     { label: "Government & Civic",   slot: 4 },
  service:   { label: "Customer Service & Retail", slot: 5 },
  facilities:{ label: "Facilities & Security", slot: 6 }
};

const STATUSES = {
  offer:      { label: "Offer accepted", rank: 5 },
  interview:  { label: "Interviewed / scheduled", rank: 4 },
  assessment: { label: "Assessment / next step", rank: 3 },
  action:     { label: "Action needed", rank: 2 },
  applied:    { label: "Applied", rank: 1 }
};

/* Interview events verified against Google Calendar (retrieved via Zapier). */
const INTERVIEWS = [
  { date: "2026-03-05", time: "10:30 AM", title: "Interview", where: "240 Ege Ave, Jersey City, NJ", company: "(company not recorded)" },
  { date: "2026-03-17", time: "2:15 PM", title: "In-person interview — Food Service Worker", where: "575 Washington Blvd, Jersey City, NJ", company: "Aramark (w/ Enid Chapman)" },
  { date: "2026-03-25", time: "12:45 PM", title: "Interview", where: "—", company: "Gnocchi" },
  { date: "2026-03-26", time: "10:00 AM", title: "Phone interview — Senior Cook (Goldman Sachs)", where: "Phone", company: "Sodexo" },
  { date: "2026-03-27", time: "12:00 PM", title: "Video interview — Kitchen Manager", where: "Indeed video", company: "TOKIODELIC" },
  { date: "2026-04-23", time: "2:45 PM", title: "Interview — Prep Cook", where: "1633 Broadway, New York, NY", company: "Din Tai Fung" },
  { date: "2026-05-05", time: "3:05 PM", title: "Interview", where: "378 Park Ave S, New York, NY", company: "Hillstone (Park Avenue)" },
  { date: "2026-05-27", time: "11:30 AM", title: "Zoom interview — Wellness & Movement Coach", where: "Zoom", company: "Success Academy (w/ Gabriel Rothkegel)" },
  { date: "2026-06-24", time: "3:00 PM", title: "Interview — Cook, FLIK", where: "200 Liberty St, New York, NY", company: "FLIK / Compass Group", outcome: "Offer accepted 6/25 🎉" }
];

/* sets: keys into SKILL_SETS (whole set matches the role's requirements)
   traits: additional exact skills matched to this specific description
   certs: certifications the posting asks for that you hold
   exp: work-history lines that qualify you
   gap: honest stretch areas vs. the posted requirements */
const APPLICATIONS = [
  // ---------------- AI & SOFTWARE ----------------
  { role: "Senior Product Engineer", company: "City of New York", date: "2026-07-16",
    source: "NYC Jobs (ref 782364)", category: "ai", status: "applied",
    note: "Confirmation received; hiring team reviewing.",
    sets: ["DEV", "AI_CORE", "CLOUD_OPS"], traits: ["Stakeholder management", "Cross-functional communication"],
    gap: "Senior-level production engineering experience is the stretch; lead with shipped AI projects." },
  { role: "Support Engineer I (NYC)", company: "Replit", date: "2026-07-05",
    source: "Ashby (2nd submission; first on 6/20)", category: "ai", status: "applied",
    note: "Applied twice — 6/20 and 7/5.",
    sets: ["DEV", "AI_CORE"], traits: ["Customer inquiry handling", "Customer communication", "Documentation", "Data-driven problem-solving"],
    gap: null },
  { role: "Neurodivergent Fellowship", company: "Palantir", date: "2026-07-02",
    source: "Lever", category: "ai", status: "applied",
    sets: ["DATA_AI", "AI_CORE"], traits: ["Python", "Data-driven problem-solving", "Research"], gap: null },
  { role: "Senior Software Developer", company: "Solovis (via ST6 Partners)", date: "2026-06-29",
    source: "Email", category: "ai", status: "assessment",
    note: "Moved forward — pre-employment assessment requested 6/29.",
    sets: ["DEV", "CLOUD_OPS"], traits: ["Data model design", "Schema design", "PostgreSQL"],
    gap: "Senior title; emphasize full-stack builds and database design work." },
  { role: "AI Product Engineer", company: "Ro", date: "2026-06-28",
    source: "Lever", category: "ai", status: "applied",
    sets: ["AI_CORE", "DEV"], traits: ["Prototypes", "Application design"], gap: null },
  { role: "AI Engineer", company: "(via Indeed)", date: "2026-06-27",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: ["AI_CORE", "DEV", "DATA_AI"], traits: [], gap: null },
  { role: "AI Enablement Engineer", company: "(via Indeed)", date: "2026-06-27",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: ["AI_CORE", "CLOUD_OPS"], traits: ["Instructor-led training (training delivery method)", "Documentation", "Process Optimization"], gap: null },
  { role: "AI Forward Deployed Engineer", company: "(via Indeed)", date: "2026-06-27",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: ["AI_CORE", "DEV"], traits: ["Customer communication", "Stakeholder management", "Prototypes"], gap: null },
  { role: "Software Engineer (AI Training)", company: "micro1", date: "2026-06-25",
    source: "micro1", category: "ai", status: "action",
    note: "AI screening interview still pending as of 6/26 reminder — complete it to advance.",
    sets: ["DEV", "AI_CORE"], traits: [], gap: null },
  { role: "AI Operations Associate", company: "(via Indeed)", date: "2026-06-25",
    source: "Indeed Apply", category: "ai", status: "applied",
    note: "Matches your #1 preferred job title.",
    sets: ["AI_CORE", "CLOUD_OPS"], traits: ["Process Optimization", "Documentation", "Attention to detail"], gap: null },
  { role: "AI Workflow & Innovation Specialist", company: "(via Indeed)", date: "2026-06-17",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: ["AI_CORE", "CLOUD_OPS"], traits: ["Process Optimization", "Creativity"], gap: null },
  { role: "AI Creative Engineer", company: "Owner.com", date: "2026-06-17",
    source: "Ashby", category: "ai", status: "applied",
    sets: ["AI_CORE"], traits: ["Creativity", "Prompt engineering", "Prototypes", "Full-stack development"], gap: null },
  { role: "Applied AI Systems Lead", company: "Schoolwide", date: "2026-06-16",
    source: "Direct email to VP", category: "ai", status: "applied",
    note: "Acknowledged by VP Stephanie Klempner same day.",
    sets: ["AI_CORE", "DEV", "CLOUD_OPS"], traits: ["System development", "Managing projects"],
    gap: "Lead title; your 4-month self-taught project portfolio is the pitch." },
  { role: "Application submitted", company: "Proofpoint", date: "2026-06-15",
    source: "Proofpoint careers", category: "ai", status: "applied",
    sets: ["CLOUD_OPS"], traits: ["Threat assessment", "Incident Reporting", "Documentation"], gap: null },
  { role: "Full-Stack Engineer 5 — AI Insights & Visualizations", company: "Netflix", date: "2026-06-14",
    source: "Netflix careers", category: "ai", status: "applied",
    sets: ["DEV", "AI_CORE", "DATA_AI"], traits: [],
    gap: "Level 5 requires years of production experience — long-shot application." },
  { role: "Junior Cloud/DevOps/SRE Engineer (Remote)", company: "Archesys", date: "2026-06-14",
    source: "Wellfound", category: "ai", status: "applied",
    sets: ["CLOUD_OPS", "DEV"], traits: ["DevOps automation", "Cloud solution engineering"], gap: null },
  { role: "Generative AI Analyst", company: "Simulmedia", date: "2026-06-09",
    source: "ZipRecruiter", category: "ai", status: "applied",
    sets: ["AI_CORE", "DATA_AI"], traits: ["Marketing"], gap: null },
  { role: "AI & IT Support Assistant", company: "Controlled Combustion Co", date: "2026-06-09",
    source: "ZipRecruiter", category: "ai", status: "action",
    note: "Application flagged incomplete — finish submission if still interested.",
    sets: ["AI_CORE", "CLOUD_OPS"], traits: ["Customer inquiry handling", "Windows"], gap: null },
  { role: "Entry-Level Software Engineer", company: "(via Indeed)", date: "2026-06-20",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: ["DEV"], traits: ["Python", "Node.js", "APIs"], gap: null },
  { role: "Data Entry Clerk (Entry Level)", company: "(via Indeed)", date: "2026-05-23",
    source: "Indeed Apply", category: "ai", status: "applied",
    sets: [], traits: ["Attention to detail", "Computer operation", "Productivity software", "Database software proficiency", "Time management", "Written communication"], gap: null },
  { role: "Technical Call Center Specialist", company: "Technogym", date: "2026-04-22",
    source: "SuccessFactors", category: "ai", status: "applied",
    sets: ["CUSTOMER"], traits: ["Group fitness", "Computer operation", "Communication skills"], gap: null },
  { role: "Customer Advisor", company: "Microsoft", date: "2026-04-05",
    source: "Microsoft careers (job 200009978)", category: "ai", status: "applied",
    sets: ["CUSTOMER", "CLOUD_OPS"], traits: ["Windows", "Azure AD", "Cross-selling"], gap: null },
  { role: "Two roles (job 210643254 & 210738172)", company: "JPMorgan Chase", date: "2026-04-30",
    source: "Oracle Cloud", category: "ai", status: "applied",
    sets: ["CORE"], traits: ["Customer service", "Computer operation"], gap: null },

  // ---------------- CULINARY ----------------
  { role: "Deli/Salad Cook — FLIK", company: "FLIK Hospitality (Compass Group)", date: "2026-06-22",
    source: "Direct email — GM Muhsin Demirkan", category: "culinary", status: "offer",
    note: "Interviewed 6/24, offer extended and ACCEPTED 6/25. 🎉",
    sets: ["COOKING", "FOOD_SAFETY", "CULINARY_EXP"], certs: ["ServSafe", "NYC Food Handlers Certificate"],
    exp: ["Grill Cook / Station Lead — Eurest (Compass Group)", "Kitchen Supervisor — Samesa"],
    traits: [], gap: null },
  { role: "Prep Cook (FT & PT)", company: "Compass Group USA", date: "2026-05-21",
    source: "Olivia/Paradox (req 1526396)", category: "culinary", status: "interview",
    note: "Interview requested 5/21.",
    sets: ["COOKING", "FOOD_SAFETY"], certs: ["ServSafe"], traits: [], gap: null },
  { role: "Prep Cook (FT)", company: "Compass Group USA", date: "2026-04-22",
    source: "Olivia/Paradox (req 1519742)", category: "culinary", status: "interview",
    sets: ["COOKING", "FOOD_SAFETY"], certs: ["ServSafe"], traits: [], gap: null },
  { role: "Experienced Chef de Partie / Line Cook", company: "(via Indeed)", date: "2026-06-03",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "CULINARY_EXP"], traits: ["Fine dining experience", "Plating"], certs: ["ServSafe"], gap: null },
  { role: "Cook", company: "Services for the Underserved", date: "2026-05-24",
    source: "iCIMS", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], certs: ["Food Handler Certification"], traits: [], gap: null },
  { role: "Line Cook — Daily Provisions", company: "Union Square Hospitality Group", date: "2026-05-20",
    source: "USHG careers", category: "culinary", status: "applied",
    sets: ["COOKING", "CULINARY_EXP"], certs: ["NYC Food Handlers Certificate"],
    exp: ["Kitchen Manager — Nom Wah Nolita"], traits: [], gap: null },
  { role: "Chef / Culinary Professional / Line Cook", company: "(via Indeed)", date: "2026-05-22",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "CULINARY_EXP"], traits: [], gap: null },
  { role: "Line Cook", company: "(via Indeed)", date: "2026-05-16",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Experienced Line Cook", company: "(via Indeed)", date: "2026-05-13",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "CULINARY_EXP"], traits: [], gap: null },
  { role: "Rooftop Kitchen Utility Steward", company: "(via Indeed)", date: "2026-05-13",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["LABOR", "FOOD_SAFETY"], traits: ["Kitchen experience", "Dishwashing"], gap: null },
  { role: "Line Cook", company: "(via Indeed)", date: "2026-05-10",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Kitchen Utility / Prep Cook", company: "(via Indeed)", date: "2026-05-07",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "LABOR"], traits: [], gap: null },
  { role: "Cook — Liberty Science Center", company: "Aramark", date: "2026-05-01",
    source: "Aramark careers", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], certs: ["ServSafe"], traits: [], gap: null },
  { role: "Back of House Staff", company: "(via Indeed)", date: "2026-05-26",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "LABOR"], traits: ["Teamwork"], gap: null },
  { role: "Utility Attendant / Potwasher", company: "(via SilkRoad)", date: "2026-06-05",
    source: "SilkRoad", category: "culinary", status: "action",
    note: "Email warned the final submission step may not have completed.",
    sets: ["LABOR", "FOOD_SAFETY"], traits: ["Dishwashing"], gap: null },
  { role: "Restaurant Staff — Park Ave", company: "Hillstone Restaurant Group", date: "2026-04-26",
    source: "SmartRecruiters", category: "culinary", status: "interview",
    note: "Resume reviewed; in-person interview held May 5 at Park Avenue (calendar-verified).",
    sets: ["COOKING", "CULINARY_EXP"], traits: ["Fine dining experience"], gap: null },
  { role: "AM Dishwasher", company: "(via Indeed)", date: "2026-04-21",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["LABOR", "FOOD_SAFETY"], traits: ["Dishwashing"], gap: null },
  { role: "Prep Cook", company: "Din Tai Fung", date: "2026-04-16",
    source: "DTF careers", category: "culinary", status: "interview",
    note: "Interview held Apr 23 at 1633 Broadway (calendar-verified).",
    sets: ["COOKING", "FOOD_SAFETY"], traits: ["Japanese cuisine", "Food steamers", "Mise en place"],
    certs: ["ServSafe"], gap: null },
  { role: "Prepared Foods Team Member (Deli / Culinary Prep)", company: "Whole Foods Market", date: "2026-04-17",
    source: "Whole Foods careers", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY", "CUSTOMER"], traits: [], gap: null },
  { role: "Food Service Worker Lead — KPMG NYC", company: "Aramark", date: "2026-04-14",
    source: "Aramark careers", category: "culinary", status: "applied",
    sets: ["COOKING", "KITCHEN_LEAD", "FOOD_SAFETY"],
    exp: ["Kitchen Supervisor — Samesa", "Operations & Management Lead"], traits: [], gap: null },
  { role: "Kitchen Manager", company: "Barcade", date: "2026-04-11",
    source: "ADP", category: "culinary", status: "applied",
    sets: ["KITCHEN_LEAD", "COOKING", "FOOD_SAFETY"],
    exp: ["Kitchen Manager — Nom Wah Nolita", "Kitchen Supervisor — Samesa"],
    certs: ["ServSafe"], traits: [], gap: null },
  { role: "Busser", company: "(via Indeed)", date: "2026-04-06",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["CUSTOMER", "LABOR"], traits: ["Restaurant experience"], gap: null },
  { role: "Senior Cook — Goldman Sachs, 30 Hudson St", company: "Sodexo", date: "2026-03-24",
    source: "Sodexo/Paradox", category: "culinary", status: "interview",
    note: "Met minimum qualifications; phone interview 3/26 — call never came, you followed up twice.",
    sets: ["COOKING", "KITCHEN_LEAD", "FOOD_SAFETY"],
    exp: ["Grill Cook / Station Lead — Eurest (Compass Group)", "Kitchen Manager — Nom Wah Nolita"],
    certs: ["ServSafe"], traits: [], gap: null },
  { role: "Kitchen Manager", company: "TOKIODELIC", date: "2026-03-22",
    source: "Indeed", category: "culinary", status: "interview",
    note: "Video interview held 3/27.",
    sets: ["KITCHEN_LEAD", "COOKING"], traits: ["Japanese cuisine"],
    exp: ["Kitchen Manager — Nom Wah Nolita"], gap: null },
  { role: "Cook (EWR)", company: "OTG Management", date: "2026-03-23",
    source: "Dayforce + hiring event invite", category: "culinary", status: "interview",
    note: "Invited to 3/26 on-the-spot hiring event, $21.45/hr start.",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Pizza Cook (Cook I)", company: "Areas USA", date: "2026-03-24",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING"], traits: ["Flat-top griddles", "Kitchen station setup"], gap: null },
  { role: "Cook", company: "Legends Global", date: "2026-03-22",
    source: "Workday", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Kitchen Manager", company: "(via Indeed)", date: "2026-03-22",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["KITCHEN_LEAD", "COOKING"], exp: ["Kitchen Manager — Nom Wah Nolita"], traits: [], gap: null },
  { role: "On-Call Cook", company: "(via Indeed)", date: "2026-03-18",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING"], traits: ["Flexibility"], gap: null },
  { role: "Dishwasher (Full Time)", company: "(via Indeed)", date: "2026-03-18",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["LABOR"], traits: ["Dishwashing"], gap: null },
  { role: "Kitchen Aide", company: "(via Indeed)", date: "2026-03-18",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "LABOR"], traits: [], gap: null },
  { role: "Food Service Worker (Full Time)", company: "Compass Group", date: "2026-03-18",
    source: "Indeed Apply", category: "culinary", status: "assessment",
    note: "2-minute assessment requested to proceed.",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Food Service Worker", company: "Aramark", date: "2026-03-08",
    source: "Aramark/Paradox", category: "culinary", status: "interview",
    note: "In-person interview 3/17 — position was filled before your arrival; you escalated in writing.",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },
  { role: "Cook", company: "Aramark", date: "2026-03-03",
    source: "Aramark careers", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], certs: ["ServSafe"], traits: [], gap: null },
  { role: "Line Cook", company: "(via Indeed)", date: "2026-03-01",
    source: "Indeed Apply", category: "culinary", status: "applied",
    sets: ["COOKING", "FOOD_SAFETY"], traits: [], gap: null },

  // ---------------- EDUCATION & COACHING ----------------
  { role: "Elementary School Wellness & Movement Coach", company: "Success Academy Charter Schools", date: "2026-05-27",
    source: "Success Academy (interview w/ Gabriel Rothkegel)", category: "education", status: "interview",
    note: "Zoom interview held 5/27; follow-up note 5/29.",
    sets: ["TEACHING", "MARTIAL_ARTS"], certs: ["Paraprofessional Certification"],
    exp: ["Head Instructor & Program Developer — Brazilian Jiu-Jitsu", "Kitchen Coordinator — Variety Boys and Girls Club"],
    traits: [], gap: null },
  { role: "ABA Male Therapist", company: "Brighter Steps ABA", date: "2026-05-20",
    source: "Apploi", category: "education", status: "applied",
    sets: ["TEACHING"], certs: ["Special Education Certification", "Paraprofessional Certification"],
    traits: ["Physical assistance for special education students", "Working with children"], gap: null },
  { role: "BT/ABA Therapist (Hoboken, M–F 3:30–6:00 PM)", company: "(via Apploi)", date: "2026-05-10",
    source: "Indeed Apply + Apploi", category: "education", status: "applied",
    note: "Schedule fits your after-school availability preference.",
    sets: ["TEACHING"], certs: ["Special Education Certification"], traits: [], gap: null },
  { role: "ABA Therapist", company: "(via Indeed)", date: "2026-05-10",
    source: "Indeed Apply", category: "education", status: "applied",
    sets: ["TEACHING"], certs: ["Special Education Certification", "Paraprofessional Certification"], traits: [], gap: null },
  { role: "Wellness Coach", company: "Services for the Underserved", date: "2026-05-24",
    source: "iCIMS", category: "education", status: "applied",
    sets: ["MARTIAL_ARTS", "TEACHING"], traits: ["Safe environment creation"], gap: null },
  { role: "Wellness Representative", company: "Restore Hyper Wellness", date: "2026-05-24",
    source: "CareerPlug", category: "education", status: "applied",
    sets: ["CUSTOMER"], traits: ["Group fitness", "Customer retention"], gap: null },
  { role: "Part-Time After-School Martial Arts Instructor", company: "(via Indeed)", date: "2026-03-14",
    source: "Indeed Apply", category: "education", status: "applied",
    sets: ["MARTIAL_ARTS", "TEACHING"],
    exp: ["Head Instructor & Program Developer — Brazilian Jiu-Jitsu"], traits: [], gap: null },
  { role: "Martial Arts Instructor", company: "(via Indeed)", date: "2026-03-04",
    source: "Indeed Apply", category: "education", status: "applied",
    sets: ["MARTIAL_ARTS", "TEACHING"],
    exp: ["Head Instructor & Program Developer — Brazilian Jiu-Jitsu"], traits: [], gap: null },
  { role: "Tech Training Course (eligibility form)", company: "Per Scholas", date: "2026-06-03",
    source: "Per Scholas", category: "education", status: "action",
    note: "Eligibility form done; enrollment steps remain. Free tech training that feeds the AI/software track.",
    sets: [], traits: ["Research", "Time management"], gap: null },

  // ---------------- GOVERNMENT & CIVIC ----------------
  { role: "City Laborer", company: "City of New York", date: "2026-05-12",
    source: "NYC Jobs (ref 779971; re-applied 5/24)", category: "civic", status: "applied",
    sets: ["LABOR"], traits: ["Manual handling", "Outdoor work", "Dependability"], gap: null },
  { role: "City Custodial Assistant", company: "City of New York", date: "2026-05-20",
    source: "NYC Jobs (ref 754916)", category: "civic", status: "applied",
    sets: ["LABOR"], traits: ["Maintaining an organized workspace", "Sanitation procedures"], gap: null },
  { role: "311 Assistant Training Associate", company: "City of New York", date: "2026-05-18",
    source: "NYC Jobs (ref 776814)", category: "civic", status: "applied",
    sets: ["CUSTOMER"], traits: ["Instructor-led training (training delivery method)", "Customer inquiry handling", "Communication skills"], gap: null },
  { role: "Employment Application (general)", company: "City of Jersey City", date: "2026-05-21",
    source: "Cognito Forms (submitted 4/10, 4/26, 5/21)", category: "civic", status: "applied",
    note: "Three submissions on file with Jersey City HR.",
    sets: ["CORE"], traits: ["Customer service", "Supervising experience"], gap: null },

  // ---------------- CUSTOMER SERVICE & RETAIL ----------------
  { role: "Retail Customer Service Associate", company: "FedEx Office (Hoboken)", date: "2026-06-10",
    source: "Paradox", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["POS systems", "Cash Handling", "Attention to detail"], gap: null },
  { role: "Men's Locker Room Attendant", company: "Life Time", date: "2026-06-08",
    source: "Workday", category: "service", status: "applied",
    sets: ["CUSTOMER", "LABOR"], traits: ["Greeting customers"], gap: null },
  { role: "Application submitted", company: "Waste Connections", date: "2026-06-05",
    source: "Waste Connections careers", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: ["Outdoor work", "Safe work practices", "Dependability"], gap: null },
  { role: "Retail Associate", company: "(via Indeed)", date: "2026-06-03",
    source: "Indeed Apply (also applied 4/8)", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: [], gap: null },
  { role: "Concierge — Citi, 388 Greenwich", company: "Aramark", date: "2026-05-21",
    source: "Aramark careers", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["Greeting customers", "Hospitality", "Communication skills"], gap: null },
  { role: "Guest Experience Associate", company: "(via Indeed)", date: "2026-04-29",
    source: "Indeed Apply", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["Hospitality"], gap: null },
  { role: "Hospitality Associate", company: "(via Indeed)", date: "2026-04-23",
    source: "Indeed Apply", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["Hospitality", "Serving"], gap: null },
  { role: "Office Services Associate", company: "RR Donnelley", date: "2026-04-08",
    source: "SmartRecruiters", category: "service", status: "applied",
    sets: ["CUSTOMER", "CLOUD_OPS"], traits: ["Productivity software", "Maintaining an organized workspace"], gap: null },
  { role: "AT&T Account Associate", company: "(via Indeed)", date: "2026-03-29",
    source: "Indeed Apply", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["Cross-selling", "Customer retention"], gap: null },
  { role: "Door Greeter", company: "The Corner Store (Landry's)", date: "2026-03-20",
    source: "iCIMS (req 2026-37420)", category: "service", status: "applied",
    sets: ["CUSTOMER"], traits: ["Greeting customers"], gap: null },
  { role: "Roles at RWJBarnabas Health (4 applications)", company: "RWJBarnabas Health", date: "2026-04-29",
    source: "HealthcareSource (3/18, 4/14, 4/16, 4/29)", category: "service", status: "applied",
    note: "Four separate applications on file.",
    sets: ["CUSTOMER", "COOKING"], traits: [], gap: null },
  // ---------------- FACILITIES & SECURITY ----------------
  { role: "Security Officer — Bank (Part Time)", company: "(via Indeed)", date: "2026-05-07",
    source: "Indeed Apply", category: "facilities", status: "applied",
    sets: ["SECURITY"], certs: ["SORA"], traits: [], gap: null },
  { role: "Terminal Security Officer — EWR", company: "Global Security Consulting Group", date: "2026-03-06",
    source: "Paycom", category: "facilities", status: "assessment",
    note: "Application status changed 3/6 — check Paycom portal.",
    sets: ["SECURITY"], certs: ["SORA"], traits: ["Threat assessment", "Patrolling"], gap: null },
  { role: "Package Sorter", company: "(via Indeed)", date: "2026-04-24",
    source: "Indeed Apply", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: ["Manual handling"], gap: null },
  { role: "Package Handler / Doorperson", company: "(via Indeed)", date: "2026-04-22",
    source: "Indeed Apply", category: "facilities", status: "applied",
    sets: ["LABOR", "CUSTOMER"], traits: ["Greeting customers"], gap: null },
  { role: "Residential Cleaning Technician", company: "Maid in JC", date: "2026-04-08",
    source: "CareerPlug", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: ["Maintaining an organized workspace", "Attention to detail"], gap: null },
  { role: "Housekeeper (Floater)", company: "Planned Companies", date: "2026-03-26",
    source: "Jobvite", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: ["Flexibility"], gap: null },
  { role: "Porter", company: "Planned Companies", date: "2026-03-18",
    source: "Jobvite", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: [], gap: null },
  { role: "Maintenance Porter", company: "(via Indeed)", date: "2026-03-04",
    source: "Indeed Apply", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: [], gap: null },
  { role: "Porter / Maintenance Worker", company: "(via Indeed)", date: "2026-03-04",
    source: "Indeed Apply", category: "facilities", status: "applied",
    sets: ["LABOR"], traits: [], gap: null }
];
